services:
  postgres:
    image: postgres:17
    container_name: alembic_postgres
    environment:
      POSTGRES_USER: alembic_user
      POSTGRES_PASSWORD: alembic_pass
      POSTGRES_DB: alembic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
