{
 "title": "gunicorn",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "process_cpu_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"localhost:9000\"}"
    }
   ]
  },
  {
   "title": "process_open_fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "targets": [
    { "expr": "process_open_fds{}" }
   ]
  },
  {
   "title": "process_max_fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 0 },
   "targets": [
    { "expr": "process_max_fds{}" }
   ]
  },
  {
   "title": "process_start_time_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    { "expr": "process_start_time_seconds{}" }
   ]
  },
  {
   "title": "process_resident_memory_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{}"
    }
   ]
  },
  {
   "title": "process_resident_memory_bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "{instance=\"localhost:9000\"}"
    }
   ]
  },
  {
   "title": "process_virtual_memory_bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 15 },
   "targets": [
    { "expr": "process_virtual_memory_bytes{}" }
   ]
  },
  {
   "title": "python_gc_objects_collected_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 19 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{}"
    }
   ]
  },
  {
   "title": "python_gc_objects_uncollectable_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total{}"
    }
   ]
  },
  {
   "title": "python_gc_collections_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 21 },
   "targets": [
    { "expr": "python_gc_collections_total{}" }
   ]
  },
  {
   "title": "python_info",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
   "targets": [
    { "expr": "python_info{}" }
   ]
  },
  {
   "title": "request_count_created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 28 },
   "targets": [
    { "expr": "request_count_created{}" }
   ]
  },
  {
   "title": "request_count_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 28 },
   "targets": [
    { "expr": "request_count_total{}" }
   ]
  }
 ]
}